// The golden corpus: see scripts/smoke-golden.mjs.
//
// Each case is one program run through the real CLI as `student.py`; its
// stdout, stderr and exit code are compared with golden/expected.txt. Cases
// are grouped by the code path they reach, so a diff names the path that
// moved. `files` are written next to the program; `stdin` is typed at it;
// `{{BUNDLE}}` in the code is the address of the sample Examplar bundle.

const B = "#level beginner";
const I = "#level intermediate";
const A = "#level advanced";

const CARS = "name,mpg\nvw,29\nhonda,33\nford,18\n";
const RIDES = "month,riders\nJan,900\nFeb,1200\nMar,\n";

const dataclass = (...lines) => ["from dataclasses import dataclass", "", ...lines];

export const CASES = [
  // ---- runtime: the catch-all and the stock rules -----------------------
  { name: "plain-ok", code: ['print("hello")'] },
  { name: "zero-division", code: ["def f(n: int) -> float:", "    return 10 / n", "", "print(f(0))"] },
  { name: "key-error-dict", code: ['d = {"a": 1}', 'print(d["b"])'] },
  { name: "key-error-sentence", code: ['raise KeyError("no such thing here")'] },
  { name: "value-error-own", code: ['raise ValueError("bad value")'] },
  { name: "runtime-no-message", code: ["raise RuntimeError()"] },
  { name: "condition-not-function", code: [B, `t = table(["month", "riders"], [["Jan", 900], ["Feb", 1200]])`, `print(t.filter("riders" < 1000))`] },
  { name: "condition-add-column", code: [B, `t = table(["month", "riders"], [["Jan", 900]])`, `print(t.add_column("busy", "riders" > 1000))`] },
  { name: "function-called-not-passed", code: [B, "def below_1k(r: dict) -> bool:", '    return r["riders"] < 1000', "", `t = table(["month", "riders"], [["Jan", 900]])`, "print(t.filter(below_1k()))"] },
  { name: "missing-dataclass", code: ["class ITunesSong:", "    title: str", "    year: int", "", 's = ITunesSong("x", 1999)'] },
  { name: "dataclass-too-few", code: dataclass("@dataclass", "class Song:", "    title: str", "    year: int", "", 's = Song("x")') },
  { name: "dataclass-too-many", code: dataclass("@dataclass", "class Song:", "    title: str", "    year: int", "", 's = Song("x", 1, 2)') },
  { name: "too-few-own", code: ["def pen_cost(num_pens: int, message: str) -> float:", "    return num_pens * 0.5", "", "print(pen_cost(3))"] },
  { name: "too-few-library", code: ["print(circle(10))"] },
  { name: "too-many-own", code: ["def double(n: int) -> int:", "    return n * 2", "", "print(double(1, 2))"] },
  { name: "too-many-library", code: ['print(circle(10, "solid", "red", 4))'] },
  { name: "method-arity", code: [`t = table(["a", "b"], [[1, 2]])`, "t.scatter_plot()"] },
  { name: "attribute-on-class", code: dataclass("@dataclass", "class Song:", "    title: str", "    year: int", "", "def title_of(s: Song) -> str:", "    return s.title", "", "print(title_of(Song))") },
  { name: "attribute-on-class-raw", code: dataclass("@dataclass", "class Song:", "    title: str", "", "print(Song.title)") },
  { name: "attribute-on-none", code: ["def deposit(b, amt):", "    b.append(amt)", "", "x = deposit([], 5)", "print(x.total)"] },
  { name: "none-attr-direct-call", code: ["def deposit(b, amt):", "    b.append(amt)", "", "print(deposit([], 5).total)"] },
  { name: "none-subscript-name", code: ["def first(xs):", "    xs.sort()", "", "r = first([3, 1])", "print(r[0])"] },
  { name: "none-loop-name", code: ["def items():", "    print(1)", "", "xs = items()", "for x in xs:", "    print(x)"] },
  { name: "none-operand-name", code: ["def total(xs):", "    s = sum(xs)", "", "t = total([1])", "print(t + 1)"] },
  { name: "none-operand-right", code: ["def total(xs):", "    s = sum(xs)", "", "t = total([1])", "print(1 + t)"] },
  { name: "none-parameter", code: ["def balance_of(acct):", "    return acct.balance", "", "print(balance_of(None))"] },
  { name: "attribute-typo-field", code: dataclass("@dataclass", "class Song:", "    title: str", "    year: int", "", 's = Song("x", 1999)', "print(s.yaer)") },
  { name: "attribute-no-fields", code: dataclass("@dataclass", "class NoInfo:", "    pass", "", "n = NoInfo()", "print(n.value)") },
  { name: "attribute-builtin", code: ["x = 5", "print(x.upper())"] },
  { name: "subscript-none", code: ["def first(xs):", "    xs.sort()", "", "print(first([3, 1])[0])"] },
  { name: "subscript-dataclass", code: dataclass("@dataclass", "class Song:", "    title: str", "    year: int", "", 's = Song("x", 1999)', 'print(s["year"])') },
  { name: "subscript-int", code: ["n = 5", "print(n[0])"] },
  { name: "loop-over-len", code: ["xs = [1, 2, 3]", "for x in len(xs):", "    print(x)"] },
  { name: "loop-over-none", code: ["def items():", "    print(1)", "", "for x in items():", "    print(x)"] },
  { name: "loop-over-int", code: ["for x in 5:", "    print(x)"] },
  { name: "concat-str-int", code: ["n = 5", 'print("total: " + n)'] },
  { name: "concat-call", code: ["def add_shipping(n: float) -> float:", "    return n + 4", "", 'print("Total: " + add_shipping(10))'] },
  { name: "concat-nested-call", code: ["def pen_cost(n, m):", "    return n * 2", "def add_shipping(n):", "    return n + 4", "", 'msg = "Total: " + add_shipping(pen_cost(10, "bravo"))'] },
  { name: "concat-value-first", code: ["n = 5", 'msg = n + " items"'] },
  { name: "concat-input", code: ['age = input("Age? ")', "print(age + 1)"], stdin: "19\n" },
  { name: "concat-list", code: ["xs = [1, 2]", 'ys = xs + "!"'] },
  { name: "concat-tuple", code: ["xs = (1, 2)", "ys = xs + 3"] },
  { name: "operand-none", code: ["def total(xs):", "    s = sum(xs)", "", "print(total([1]) + 1)"] },
  { name: "operand-str-list", code: ['print("a" - [1])'] },
  { name: "operand-dict", code: ["print({} * 2.5)"] },
  { name: "compare-str-int", code: ['print("5" < 3)'] },
  { name: "compare-csv", code: ['t = load_table("cars.csv")', 'print(t.filter(lambda r: r["mpg"] > 20))'], files: { "cars.csv": CARS } },
  { name: "compare-none", code: ["def f():", "    pass", "", "print(f() > 3)"] },
  { name: "bad-int-word", code: ['n = int("nineteen")'] },
  { name: "bad-int-input", code: ['n = int(input("How many? "))', "print(n)"], stdin: "nineteen\n" },
  { name: "bad-int-input-blank", code: ['n = int(input("How many? "))'], stdin: "\n" },
  { name: "bad-int-csv-blank", code: ['t = load_table("rides.csv")', 't2 = t.transform_column("riders", int)', "print(t2)"], files: { "rides.csv": RIDES } },
  { name: "index-range", code: ["nums = [1, 2, 3]", "print(nums[5])"] },
  { name: "index-range-in-fn", code: ["def third(xs: list) -> int:", "    return xs[3]", "", "print(third([1, 2]))"] },
  { name: "index-range-string", code: ['word = "hi"', "print(word[9])"] },
  { name: "not-callable-int", code: ["width = 3", "print(3(width))"] },
  { name: "not-callable-name", code: ["total = 5", "print(total(2))"] },
  { name: "pattern-arity", code: dataclass("@dataclass", "class Boa:", "    name: str", "    length: int", "", 'b = Boa("x", 3)', "match b:", "    case Boa(n, l, extra):", "        print(n)") },
  { name: "missing-comma-rows", code: ["rows = [", '    ("a", 1)', '    ("b", 2)', "]"] },
  { name: "recursion", code: ["def count(n: int) -> int:", "    return count(n + 1)", "", "print(count(0))"] },
  { name: "discarded-add-column", code: [`employees = table(["name", "hours"], [["a", 10]])`, 'employees.add_column("pay", lambda r: r["hours"] * 15)', 'print(employees.column("pay"))'] },
  { name: "discarded-add-column-beginner", code: [B, `employees = table(["name", "hours"], [["a", 10]])`, 'employees.add_column("pay", lambda r: r["hours"] * 15)', 'print(employees.column("pay"))'] },
  { name: "discarded-add-column-in-fn-intermediate", code: [I, "def pay(employees: Table) -> list:", '    employees.add_column("pay", lambda r: r["hours"] * 15)', '    return employees.column("pay")', "", 'print(pay(table(["name", "hours"], [["a", 10]])))'] },
  { name: "discarded-add-column-in-fn-beginner", code: [B, "def pay(employees: Table) -> list:", '    employees.add_column("pay", lambda r: r["hours"] * 15)', '    return employees.column("pay")', "", 'print(pay(table(["name", "hours"], [["a", 10]])))'] },
  { name: "uneven-columns", code: ["import pandas as pd", 'df = pd.DataFrame({"a": [1, 2], "b": [1]})'] },
  { name: "pandas-key-error", code: ["import pandas as pd", 'df = pd.DataFrame({"rating": [1, 2]})', 'print(df["ratings"])'] },
  { name: "handler-called", code: ["def draw_dog(n: int) -> Image:", '    return circle(10, "solid", "red")', "", "animate(to_draw=draw_dog(0))"] },
  { name: "error-in-library-callback", code: [`t = table(["a"], [[1], [2]])`, 'print(t.add_column("b", lambda r: r["a"] / 0))'] },
  { name: "error-deep-stack", code: ["def a(n):", "    return b(n)", "def b(n):", "    return c(n)", "def c(n):", "    return n / 0", "", "print(a(1))"] },

  // ---- type checking (typeguard) ----------------------------------------
  { name: "tc-argument", code: [B, "def double(n: int) -> int:", "    return n * 2", "", 'print(double("4"))'] },
  { name: "tc-argument-float", code: [B, "def half(n: float) -> float:", "    return n / 2", "", 'print(half("4"))'] },
  { name: "tc-return-none", code: [B, "def shout(word: str) -> str:", "    word.upper()", "", 'print(shout("hi"))'] },
  { name: "tc-return-print", code: [B, "def order(order_amt: float) -> float:", "    if order_amt > 10:", "        return order_amt", "    else:", "        print(order_amt + 4)", "", "print(order(5))"] },
  { name: "tc-return-append", code: [B, "def add(xs: list, x: int) -> list:", "    return xs.append(x)", "", "print(add([], 1))"] },
  { name: "tc-return-wrong", code: [B, "def name_of(n: int) -> str:", "    return n", "", "print(name_of(3))"] },
  { name: "tc-match-no-case", code: [B, ...dataclass("@dataclass", "class Dog:", "    name: str", "@dataclass", "class Cat:", "    name: str", "", "Pet = Dog | Cat", "", "def sound(p: Pet) -> str:", "    match p:", "        case Dog(n):", '            return "woof"', "", 'print(sound(Cat("x")))')] },
  { name: "tc-union-argument", code: [B, "def f(x: int | None) -> int:", "    return 1", "", 'print(f("a"))'] },
  { name: "tc-list-element", code: [B, "def total(lst: list[float]) -> float:", "    return sum(lst)", "", 'print(total(["1", 2.0]))'] },
  { name: "tc-dict-value", code: [B, "def total(d: dict[str, int]) -> int:", "    return sum(d.values())", "", 'print(total({"a": "1"}))'] },
  { name: "tc-bool-as-int", code: [B, "def double(n: int) -> int:", "    return n * 2", "", "print(double(True))"] },
  { name: "tc-bool-as-int-advanced", code: [A, "def double(n: int) -> int:", "    return n * 2", "", "print(double(True))"] },
  { name: "tc-field", code: [B, ...dataclass("@dataclass", "class Song:", "    title: str", "    year: int", "", 's = Song("x", "1999")')] },
  { name: "tc-field-swapped", code: [B, ...dataclass("@dataclass", "class Song:", "    title: str", "    year: int", "", 's = Song(1999, "x")')] },
  { name: "tc-class-itself", code: [B, ...dataclass("@dataclass", "class Song:", "    title: str", "", "def t(s: Song) -> str:", "    return s.title", "", "print(t(Song))")] },
  { name: "tc-row-is-dict", code: [B, "def big(r: int) -> bool:", '    return r["a"] > 1', "", `t = table(["a"], [[1]])`, "print(t.filter(big))"] },
  { name: "tc-filter-returns", code: [B, "def keep(r: dict) -> bool:", '    return r["a"]', "", `t = table(["a"], [[1]])`, "print(t.filter(keep))"] },
  { name: "tc-reactor-init", code: [B, "def draw(n: int) -> Image:", '    return circle(10, "solid", "red")', "", 'r = reactor(init="zero", to_draw=draw)', "r.interact()"] },
  { name: "tc-raw-unchecked", code: ["def double(n: int) -> int:", "    return n * 2", "", 'print(double("4"))'] },
  { name: "tc-intermediate", code: [I, "def double(n: int) -> int:", "    return n * 2", "", 'print(double("4"))'] },
  { name: "tc-annotation-string-type", code: [B, "def f(n: string) -> int:", "    return 1", "", "print(f(1))"] },

  // ---- names --------------------------------------------------------------
  { name: "name-undefined", code: ["print(totl)"] },
  { name: "name-typo", code: ["total = 10", "print(Total)"] },
  { name: "name-typo-close", code: ["width = 10", "print(widht)"] },
  { name: "name-import-pd", code: ['df = pd.DataFrame({"a": [1]})'] },
  { name: "name-import-math", code: ["print(math.sqrt(4))"] },
  { name: "name-defined-later", code: ["print(double(2))", "", "def double(n):", "    return n * 2"] },
  { name: "name-forward-annotation", code: [B, ...dataclass("@dataclass", "class Node:", "    value: int", "    rest: NumList", "", "NumList = Node | None")] },
  { name: "name-free-variable", code: ["def outer():", "    def inner():", "        return title", "    r = inner()", '    title = "x"', "    return r", "", "outer()"] },
  { name: "name-unbound-local", code: ["count = 0", "def bump():", "    count = count + 1", "", "bump()"] },
  { name: "name-passed-result", code: [`t = table(["riders"], [[1]])`, "def below_1k(r):", '    return r["riders"] < 1000', "print(t.filter(below_1k(r)))"] },
  { name: "name-in-function", code: ["def f(n: int) -> int:", "    return n + missing", "", "print(f(1))"] },
  { name: "name-deep", code: ["def g():", "    if True:", "        return missing", "g()"] },

  // ---- syntax -------------------------------------------------------------
  { name: "syntax-else-if", code: ["x = 3", "if x > 2:", '    print("a")', "else if x > 1:", '    print("b")'] },
  { name: "syntax-assign-in-if", code: ["x = 5", "if x = 5:", "    print(x)"] },
  { name: "syntax-class-keyword", code: ["class = 30"] },
  { name: "syntax-curly-quote", code: ["print(“hello”)"] },
  { name: "syntax-tab", code: ["def f():", "    x = 1", "\ty = 2", "    return x"] },
  { name: "syntax-missing-colon", code: ["def f()", "    return 1"] },
  { name: "syntax-unclosed", code: ["print((1, 2)", "x = 3"] },
  { name: "syntax-indent", code: ["def f():", "return 1"] },
  { name: "syntax-case-capture", code: dataclass("@dataclass", "class Boa:", "    name: str", "", "def f(b):", "    match b:", "        case Boa:", "            return 1", "        case _:", "            return 2") },
  { name: "syntax-case-capture-tests", code: dataclass("@dataclass", "class Boa:", "    name: str", "", "def f(b):", "    match b:", "        case Boa:", "            return 1", "        case _:", "            return 2", "", "def test_f():", '    assert f(Boa("x")) == 1') },
  { name: "syntax-warning-unrun", code: ["def area(w):", "    return 3(w)", "", 'print("fine")'] },
  { name: "syntax-warning-run", code: ["print(3(4))"] },
  { name: "syntax-row-missing-comma", code: [`t = table(["a", "b"], [`, `    ["x", 1]`, `    ["y", 2]`, "])"] },
  { name: "syntax-beginner", code: [B, "x = (1, 2"] },

  // ---- level header -------------------------------------------------------
  { name: "header-misspelled", code: ["#level begginer", 'print("x")'] },
  { name: "header-capital", code: ["#level Beginner", 'print("x")'] },
  { name: "header-bare", code: ["#level", 'print("x")'] },
  { name: "header-no-space", code: ["#levelbeginner", 'print("x")'] },
  { name: "header-not-first", code: ['print("x")', B] },
  { name: "header-unknown-word", code: ["#level easy", 'print("x")'] },

  // ---- static findings ----------------------------------------------------
  { name: "st-reassignment", code: [B, "total = 1", "total = 2"] },
  { name: "st-reassignment-intermediate", code: [I, "total = 1", "total = 2"] },
  { name: "st-reassignment-in-fn", code: [B, "def f():", "    x = 1", "    x = 2", "    return x"] },
  { name: "st-shadowing", code: [B, "x = 1", "def f():", "    x = 2", "    return x"] },
  { name: "st-shadowing-builtin", code: [B, "list = [1, 2]"] },
  { name: "st-shadowing-library", code: [B, "def circle(r):", "    return r"] },
  { name: "st-shadowing-library-table", code: [B, "table = 3"] },
  { name: "st-global", code: [I, "count = 0", "def bump():", "    global count", "    count = count + 1"] },
  { name: "st-nonlocal", code: [B, "def outer():", "    n = 0", "    def inner():", "        nonlocal n", "        n = 1", "    inner()"] },
  { name: "st-unused-comparison", code: [B, "def double(n: int) -> int:", "    return n * 2", "", "def test_double():", "    double(2) == 4"] },
  { name: "st-unused-value", code: [B, "def order(order_amt: float) -> float:", "    order_amt + 8", "    return order_amt"] },
  { name: "st-unused-value-field", code: [B, ...dataclass("@dataclass", "class Account:", "    balance: float", "", "def deposit(ac: Account, amt: float) -> Account:", "    ac.balance + amt", "    return ac")] },
  { name: "st-assert-tuple", code: [B, "def test_total():", "    assert(1, 2)"] },
  { name: "st-method-not-called", code: [B, 'movies = table(["rating"], [[1], [2]])', "def avg() -> int:", "    return movies.count", "print(avg())"] },
  { name: "st-annotation-not-a-type", code: [B, "def f(t: table) -> int:", "    return 1"] },
  { name: "st-test-not-named", code: [B, "def double(n: int) -> int:", "    return n * 2", "", "def check_double():", "    assert double(2) == 4", "", 'print("ran")'] },
  { name: "st-field-no-type", code: [B, ...dataclass("@dataclass", "class Song:", "    title: str", "    year = 1999")] },
  { name: "st-field-assigned-type", code: [B, ...dataclass("@dataclass", "class Song:", "    title: str", "    year = int")] },
  { name: "st-class-needs-dataclass", code: [B, "class Song:", "    title: str", "    year: int"] },
  { name: "st-compared-with-class", code: [B, ...dataclass("@dataclass", "class Boa:", "    name: str", "", "def is_boa(a) -> bool:", "    return a == Boa")] },
  { name: "st-duplicate-function", code: [B, "def f():", "    return 1", "", "def f():", "    return 2"] },
  { name: "st-duplicate-class", code: [B, ...dataclass("@dataclass", "class A:", "    x: int", "@dataclass", "class A:", "    y: int")] },
  { name: "st-several", code: [B, "total = 1", "total = 2", "list = 3", "def test_x():", "    assert(1, 2)"] },
  { name: "st-warning-and-error", code: [B, 'm = table(["r"], [[1]])', "def avg():", "    return m.count", "total = 1", "total = 2"] },

  // ---- images ---------------------------------------------------------------
  { name: "img-colour-typo", code: ['rectangle(30, 40, "solid", "bleu")'] },
  { name: "img-colour-nonsense", code: ['circle(5, "solid", "zzzzzzz")'] },
  { name: "img-colour-number", code: ['rectangle(30, 40, "solid", 50)'] },
  { name: "img-colour-range", code: ['circle(5, "solid", (300, 0, 0))'] },
  { name: "img-mode", code: ['circle(5, "outilne", "red")'] },
  { name: "img-size-string", code: ['circle("5", "solid", "red")'] },
  { name: "img-size-negative", code: ['rectangle(-5, 4, "solid", "red")'] },
  { name: "img-scale-zero", code: ['scale(0, circle(5, "solid", "red"))'] },
  { name: "img-rotate-order", code: ['rotate(circle(5, "solid", "red"), 45)'] },
  { name: "img-add", code: ['a = circle(5, "solid", "red")', "b = a + a"] },
  { name: "img-beside-string", code: ['a = circle(5, "solid", "red")', 'beside(a, "austria")'] },
  { name: "img-beside-list", code: ['a = circle(5, "solid", "red")', "beside([a, a])"] },
  { name: "img-place", code: ['a = circle(5, "solid", "red")', 'beside_align("upper", a, a)'] },
  { name: "img-load-missing", code: ['load_image("dog.png")'] },
  { name: "img-ok", code: ['print(circle(5, "solid", "red"))'] },

  // ---- tables ---------------------------------------------------------------
  { name: "tbl-row-length", code: [`t = table(["a", "b"], [[1, 2], [3]])`] },
  { name: "tbl-row-length-lines", code: ["t = table(", '    ["a", "b"],', "    [", "        [1, 2],", "        [3, 4],", "        [5],", "    ],", ")"] },
  { name: "tbl-columns-string", code: [`t = table("a, b", [[1, 2]])`] },
  { name: "tbl-rows-not-nested", code: [`t = table(["a", "b"], [1, 2])`] },
  { name: "tbl-duplicate-column", code: [`t = table(["a", "a"], [[1, 2]])`] },
  { name: "tbl-row-no-column", code: [`t = table(["month", "riders"], [["Jan", 1]])`, 'print(t.filter(lambda r: r["rider"] > 1))'] },
  { name: "tbl-row-attribute", code: [`t = table(["month", "riders"], [["Jan", 1]])`, "print(t.filter(lambda r: r.riders > 1))"] },
  { name: "tbl-row-by-name", code: [`t = table(["month"], [["Jan"]])`, 'print(t.row("Mar"))'] },
  { name: "tbl-row-range", code: [`t = table(["month"], [["Jan"]])`, "print(t.row(5))"] },
  { name: "tbl-no-column", code: [`t = table(["Month"], [["Jan"]])`, 'print(t.column("month"))'] },
  { name: "tbl-no-column-prefix", code: [`t = table(["hours-worked"], [[1]])`, 'print(t.column("hours"))'] },
  { name: "tbl-filter-arity", code: [`t = table(["a"], [[1]])`, "def keep(r, x):", "    return True", "print(t.filter(keep))"] },
  { name: "tbl-filter-not-function", code: [`t = table(["a"], [[1]])`, "print(t.filter(3))"] },
  { name: "tbl-filter-non-bool", code: [`t = table(["a"], [[1]])`, 'print(t.filter(lambda r: r["a"]))'] },
  { name: "tbl-order-by-string-bool", code: [`t = table(["a"], [[1]])`, 'print(t.order_by("a", ascending="False"))'] },
  { name: "tbl-order-by-typo", code: [`t = table(["a"], [[1]])`, 'print(t.order_by("b"))'] },
  { name: "tbl-select-string", code: [`t = table(["name", "x"], [["a", 1]])`, 'print(t.select_columns("name"))'] },
  { name: "tbl-mean-text", code: ['t = load_table("cars.csv")', 'print(t.mean("mpg"))'], files: { "cars.csv": CARS } },
  { name: "tbl-load-missing", code: ['t = load_table("car.csv")'], files: { "cars.csv": CARS } },
  { name: "tbl-load-missing-none", code: ['t = load_table("data.csv")'] },
  { name: "tbl-ok", code: ['t = load_table("cars.csv")', 'print(t.transform_column("mpg", float).mean("mpg"))', "t"], files: { "cars.csv": CARS } },

  // ---- tests ----------------------------------------------------------------
  { name: "test-pass", code: ["def double(n):", "    return n * 2", "", "def test_double():", "    assert double(2) == 4"] },
  { name: "test-fail", code: ["def double(n):", "    return n * 3", "", "def test_double():", "    assert double(2) == 4"] },
  { name: "test-float", code: ["def tax(n):", "    return n * 0.31", "", "def test_tax():", "    assert tax(3) == 0.93"] },
  { name: "test-print-shown", code: [B, "def shout(word: str) -> str:", "    return None", "", "def test_shout():", '    print("about to call shout")', '    assert shout("hi") == "HI!"'] },
  { name: "test-error-concat", code: ["def add(xs):", '    return xs + "!"', "", "def test_add():", "    assert add([1]) == [1]"] },
  { name: "test-error-typecheck", code: [B, "def shout(word: str) -> str:", "    return word.upper()", "", "def test_shout():", "    assert shout(3) == 3"] },
  { name: "test-error-name", code: ["def test_x():", "    assert totl == 1"] },
  { name: "test-error-index", code: ["def third(xs):", "    return xs[3]", "", "def test_third():", "    assert third([1, 2]) == 3"] },
  { name: "test-error-key", code: ["def test_d():", '    d = {"a": 1}', '    assert d["b"] == 1'] },
  { name: "test-error-recursion", code: ["def f(n):", "    return f(n)", "", "def test_f():", "    assert f(1) == 1"] },
  { name: "test-params", code: ["def pen_cost(n):", "    return n", "", "def test_pen_cost(n):", "    assert pen_cost(n) == n"] },
  { name: "test-async", code: ["async def test_a():", "    assert True"] },
  { name: "test-class", code: ["class TestThings:", "    def test_one(self):", "        assert 1 == 2"] },
  { name: "test-top-level-error", code: ["x = 1 / 0", "", "def test_a():", "    assert True"] },
  { name: "test-and-program-error", code: ["def double(n):", "    return n * 2", "", "def test_double():", "    assert double(2) == 4", "", "print(double(undefined_name))"] },
  { name: "test-skip", code: ["import pytest", "", "def test_s():", '    pytest.skip("later")'] },
  { name: "test-approx", code: ["import pytest", "", "def test_a():", "    assert 0.1 + 0.2 == pytest.approx(0.3)"] },
  { name: "test-forward-ref", code: dataclass("@dataclass", "class Node:", "    value: int", '    rest: "NumList"', "", "NumList = Node | None", "", "def test_n():", "    assert Node(1, None).value == 1") },

  // ---- examplar ------------------------------------------------------------
  // `{{BUNDLE}}` is samples/examplar_bundle, built and served by the test.
  { name: "ex-tests-first", code: [B, "#examplar {{BUNDLE}}", "", "def test_initials_two_names():", '    assert initials("Ada Lovelace") == "A.L."', "", "def test_longest_picks_the_longest():", '    assert longest(["cat", "hippo", "ox"]) == "hippo"'] },
  { name: "ex-wrong-expectation", code: [B, "#examplar {{BUNDLE}}", "", "def test_initials_lower():", '    assert initials("ada lovelace") == "a.l."', "", "def test_longest():", '    assert longest(["cat", "hippo"]) == "hippo"'] },
  { name: "ex-test-raises", code: [B, "#examplar {{BUNDLE}}", "", "def test_initials_from_file():", '    name = open("name.txt").read()', '    assert initials(name) == "A.L."', "", "def test_longest():", '    assert longest(["cat", "hippo"]) == "hippo"'], files: { "name.txt": "Ada Lovelace" } },
  { name: "ex-thorough", code: [B, "#examplar {{BUNDLE}}", "", "def test_initials():", '    assert initials("Ada Lovelace") == "A.L."', '    assert initials("ada lovelace") == "A.L."', '    assert initials("Grace") == "G."', '    assert initials("  Ada   Lovelace ") == "A.L."', "", "def test_longest():", '    assert longest(["cat", "hippo", "ox"]) == "hippo"', '    assert longest(["cat", "dog"]) == "cat"', '    assert longest([]) == ""'] },
  { name: "ex-with-own-code", code: [B, "#examplar {{BUNDLE}}", "", "def initials(name: str) -> str:", '    return "".join(w[0].upper() + "." for w in name.split())', "", "def longest(words: list) -> str:", '    return max(words, key=len) if words else ""', "", "def test_initials():", '    assert initials("Ada Lovelace") == "A.L."', "", "def test_longest():", '    assert longest(["cat", "hippo"]) == "hippo"', "", 'print(initials("Grace"))'] },
  { name: "ex-no-tests", code: [B, "#examplar {{BUNDLE}}", "", 'print("nothing yet")'] },
  { name: "ex-plain-http", code: [B, "#examplar http://example.com/hw.json", "", "def test_a():", "    assert True"] },
  { name: "ex-unreachable", code: [B, "#examplar http://localhost:9/hw.json", "", "def test_a():", "    assert True"] },
  { name: "ex-two-directives", code: [B, "#examplar {{BUNDLE}}", "#examplar {{BUNDLE}}", "", "def test_a():", "    assert True"] },

  // ---- input --------------------------------------------------------------
  { name: "input-ok", code: ['name = input("Name? ")', 'print("hi", name)'], stdin: "Ada\n" },
  { name: "input-eof", code: ['a = input("A? ")', 'b = input("B? ")', "print(a, b)"], stdin: "x\n" },

  // ---- prompt-only and reactor-only paths are covered by the session tests;
  // ---- these pin what the CLI says about them.
  { name: "reactor-cli", code: ["def draw(n: int) -> Image:", '    return circle(10, "solid", "red")', "", "animate(draw)"] },
  { name: "reactor-not-started", code: ["def draw(n: int) -> Image:", '    return circle(10, "solid", "red")', "", "r = reactor(init=0, to_draw=draw)"] },
];
